### ISSUE TITLE
Doesn't work with locally-installed Elm 0.18

### ISSUE THREAD

**Issue by willnwhite** [avh4/elm-upgrade#12]
elm-upgrade gave me `ERROR: Elm 0.18 required, but found Elm Platform 0.17.1`.
I'd installed 0.18 locally as per [this advice](https://groups.google.com/d/msg/elm-dev/XS_IdIUnLsw/Mmo7EjWVBgAJ) for using Elm in production.

**Comment by avh4** [comment]
What do you get when running `elm` directly from the commandline?  And what do you get for `which elm` ?

**Comment by eeue56** [comment]
@avh4, we should look for node_modules in the folder and default to using that version of elm if found. I'll make a PR in a minute

**Comment by willnwhite** [comment]
@avh4 
`elm` gives me `Elm Platform 0.17.1 - a way to run all Elm tools`.
`node_modules/.bin/elm` give me `Elm Platform 0.18.0 - a way to run all Elm tools`.
`which elm` gives me `/usr/local/bin/elm`.
`which node_modules/.bin/elm` gives me `node_modules/.bin/elm`.

**Comment by avh4** [comment]
ah, I see.  (I hadn't understood what "locally-installed") meant

**Comment by avh4** [comment]
(@eeue56, FYI I'll be publishing a new elm-upgrade release tonight after releasing elm-format-0.5.2)

**Comment by avh4** [comment]
Fixed in #16.  Will be in 0.18.5 release (to be published in a few minutes)

**Comment by willnwhite** [comment]
Ah, yes, I should have said installed in node_modules/.bin, not locally-installed!
