### ISSUE TITLE
List.range conversion for [Namespace.exp1..Namespace.exp2]

### ISSUE THREAD

**Issue by manuscrypt** [avh4/elm-upgrade#14]
Not sure, if this should be on elm-format after the last one I posted.
Here is the piece of code that didn't convert correctly:

```
 let
        all =
            List.map (String.fromChar << Char.fromCode)
                [Ascii.fromCode..Ascii.toCode]
```

where 

```
fromCode : Int
fromCode =
    32


toCode : Int
toCode =
    126
```

Thanks again for a great tool!

**Comment by eeue56** [comment]
This should be on elm format :+1:
