### ISSUE TITLE
Don't look in node_modules

### ISSUE THREAD

**Issue by jackfranklin** [avh4/elm-upgrade#17]
gulp-elm for example has a Test.elm file that it tries to upgrade, which isn't needed. I'd suggest just avoiding that directory entirely.

**Comment by jackfranklin** [comment]
I'm happy to make this PR too btw, just raising it now while I remember! If no one beats me to it I can do it tomorrow.

**Comment by avh4** [comment]
elm-upgrade only runs elm-format on folders that are listed as source-directories in the elm-package.json.  However, if `.` is listed, then `elm-format .` will find files in node_modules.  I think this issue should be moved to elm-format: https://github.com/avh4/elm-format/issues

**Comment by jackfranklin** [comment]
Ah, I'll open an issue there. I think that my Haskell knowledge (or lack of) will prevent me doing the PR unfortunately. I'll close this.
