### ISSUE TITLE
Weird upgrade.

### ISSUE THREAD

**Issue by akoppela** [avh4/elm-upgrade#29]
I've noticed following change with upgrade. 

![image](https://user-images.githubusercontent.com/56569/39878694-8f4452c2-54ab-11e8-9774-020738e37ee0.png)

**Comment by avh4** [comment]
Fixed in 8faccdf, and will be in a future version of elm-upgrade, after a new rc binary release of elm-format is made.

Thanks for the report!

**Comment by avh4** [comment]
(oops, meant to close the elm-format bug)

**Comment by akoppela** [comment]
Thank you man!

**Comment by avh4** [comment]
Fixed in 0.19.0-rc8
