### ISSUE TITLE
Should it be an error instead of a warning when a dependency doesn't support the target Elm version?

### ISSUE THREAD

**Issue by avh4** [avh4/elm-upgrade#3]
For example, a project upgrade shows:

`WARNING: rtfeldman/elm-validate has not been upgraded to 0.18 yet!`

But then also indicates success at the end.  Should this instead be a fatal error for the upgrade?

cc @eeue56

**Comment by eeue56** [comment]
It should definitely not be a fatal error - but maybe it should log it as an error. 

The reasoning being, if you can upgrade 90% of the deps, that's great. Then you want to handle the package that isn't upgraded yet somehow. Maybe we can add a link so they can make a PR or something.

**Comment by avh4** [comment]
Maybe slightly change the message to something like "The author of rtfeldman/elm-validate hasn't yet published a version that's compatible with Elm 0.18"  to sort of hint at what needs to be done

**Comment by avh4** [comment]
Closed via #5
