### ISSUE TITLE
404 new-packages not found?

### ISSUE THREAD

**Issue by noelrappin** [avh4/elm-upgrade#45]
Am I doing something wrong here?

```
$ elm-upgrade                                                                    
{ HTTPError: Response code 404 (Not Found)
    at stream.catch.then.data (/usr/local/lib/node_modules/elm-upgrade/node_modules/got/index.js:123:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message: 'Response code 404 (Not Found)',
  host: 'package.elm-lang.org',
  hostname: 'package.elm-lang.org',
  method: 'GET',
  path: '/new-packages',
  statusCode: 404,
  statusMessage: 'Not Found' }
ERROR: Unable to connect to http://package.elm-lang.org.  Please try again later.
```

**Comment by charukiewicz** [comment]
Experiencing the same issue.

Looks like the page is indeed returning a 404: https://package.elm-lang.org/new-packages

**Comment by avh4** [comment]
Ah, the Elm 0.19 version of elm-upgrade hasn't been published yet.  It sounds like people here are using the 0.18 version.  The new version should be published in a few hours.

**Comment by charukiewicz** [comment]
Thanks @avh4! When you are done, would you be able to upload a binary as a GitHub release in addition to publishing on npm? A single `.tar.gz` file is a lot easier to work with than the npm utility.
