### ISSUE TITLE
Don't do the 0.18 -> 0.19 upgrade if `elm.json` already exists

### ISSUE THREAD

**Issue by avh4** [avh4/elm-upgrade#49]
Actually, it should probably move it to `old-elm-package.json` in case the user doesn't ahve version control.

The current behavior is that elm-package.json is left, but it is also strangely modified with some of the dependencies removed.

**Comment by Qqwy** [comment]
One of the things it modifies is changing the `source-directories` back to `"."`.

**Comment by avh4** [comment]
Hmm... it looks like elm-upgrade already does this, but it seems like people then accidentally run Elm 0.18 commands which recreate it, or something like that.

**Comment by avh4** [comment]
Yeah, this seems to be caused by people running Elm 0.18 commands, which silently recreate the elm-package.json.  However, elm-upgrade-0.19.3 will no longer attempt the 0.18 upgrade if an elm.json is found, so this will hopefully no longer confuse elm-upgrade users.
