### ISSUE TITLE
README typo?

### ISSUE THREAD

**Issue by simonh1000** [avh4/elm-upgrade#78]
where it says `npm install elm-format@elm0.19.0` I think it should skip the `@...` as the version is 0.8.1?

**Comment by avh4** [comment]
The `@elm0.19.0` is a tag to make sure you get a version of elm-format that supports Elm 0.19.  (You can also use `@elm0.18.0` to get the latest elm-format version that still supported Elm 0.19.)

**Comment by simonh1000** [comment]
thx
