### ISSUE TITLE
Missing parens when inserting Range

### ISSUE THREAD

**Issue by manuscrypt** [avh4/elm-upgrade#8]
@av: I just tried to `elm-upgrade` a project (elm-color-extra, obvisouly not mine), and noticed this diff:

```
-            List.map2 (\i cl -> ( (toFloat i / toFloat l), cl )) [0..l] palette
+            List.map2 (\i cl -> ( (toFloat i / toFloat l), cl )) List.range 0 l palette
```

And the compiler complains about the number of arguments to map2.

**Comment by avh4** [comment]
Ah, this bug should go to -> https://github.com/avh4/elm-format/issues

**Comment by avh4** [comment]
Fixed in https://github.com/avh4/elm-format/issues/271  will be in elm-format 0.5.1-alpha
